bmc-toolbox/bmclib

devices/interfaces.go, internal/sshclient/sshclient.go, providers/dell/m1000e/actions.go, providers/dell/m1000e/configure.go, providers/dell/m1000e/m1000e.go, providers/dell/m1000e/m1000e_test.go, providers/dell/m1000e/setupConnections.go, providers/hp/c7000/actions.go, providers/hp/c7000/c7000.go, providers/hp/c7000/c7000_test.go, providers/hp/c7000/configure.go, providers/hp/c7000/setupConnections.go, providers/hp/c7000/xmlhelpers.go
Implement #38 and #39 ssh support for hp and dell chassis. I think we need a better pattern for the login methods, but it works for now.
=> Ssh support

providers/dell/idrac8/setupConnections.go, providers/dell/idrac9/setupConnections.go, providers/dell/m1000e/setupConnections.go, providers/hp/c7000/setupConnections.go, providers/hp/ilo/setupConnection.go, providers/supermicro/supermicrox10/setupConnection.go
password, also c7000 wasn't return login failed when can't parse the
xmlToken
=> fixed a bug that could lead to never authenticate after updating the

devices/interfaces.go, providers/dell/idrac8/setupConnections.go, providers/dell/idrac9/setupConnections.go, providers/hp/ilo/setupConnection.go
- expose PowerCycleBmc() method
-  fix logging message for bmc ssh connections
=> Minor fixes

internal/httpclient/httpclient.go, providers/hp/c7000/configure.go, providers/hp/c7000/setupConnections.go
Finally found the cause for the panics, fixed in e9126da
=> Fix c7000 connection issues

cfgresources/cfgresources.go, providers/dell/idrac8/configure.go, providers/dell/idrac9/idrac9.go, providers/dell/idrac9/setupConnections.go, providers/hp/c7000/configure.go, providers/hp/c7000/xmlmodel.go, providers/hp/ilo/configure.go, providers/hp/ilo/model.go
- ilo4,5: Add support for license configuration.
- c7000, idrac8: support LDAP group removal
- idrac9: fix configuration PUT actions.
=> Various fixes and features

providers/dell/idrac8/configure.go, providers/dell/idrac8/helpers.go, providers/dell/idrac8/idrac8.go, providers/dell/idrac8/model.go, providers/dell/idrac8/query.go
We now retrieve the list of current users and add/update based on config.
=> Idrac8 fix user account management.

README.md, logging/logging.go, providers/dell/idrac8/query.go
- Adds DEBUG_BMCLIB env var
- Fixes idrac8 screen preview capture
=> misc fixes

providers/hp/ilo/setupConnection.go
https://github.com/bmc-toolbox/bmclib/issues/60
=> ilo: fixes logout on ilo4,5

.travis.yml, discover/discover.go, providers/dell/idrac8/idrac8_test.go, providers/dell/idrac9/idrac9_test.go, providers/dell/m1000e/m1000e_test.go, providers/dummy/ibmc/ibmc.go, providers/dummy/ibmc/ibmc_test.go, providers/hp/c7000/c7000_test.go, providers/hp/ilo/ilo_test.go, providers/supermicro/supermicrox10/supermicrox10_test.go
- Update travis build to run tests sequentially
- Fix up dummy provider to implement Bmc interface, add test
- Update various providers to test for Configure, BmcChassisSetup interfaces.
=> Test configure interface

providers/dell/idrac8/query.go, providers/dell/idrac9/configure.go, providers/dell/idrac9/model.go, providers/dell/idrac9/query.go, providers/dummy/ibmc/ibmc.go, providers/hp/ilo/model.go, providers/hp/ilo/query.go
- Fixes travis build issues - https://travis-ci.org/bmc-toolbox/bmclib/builds/505201007
- Updates idrac9 CSR configuration to support SANs.
=> Idrac9 and travis build fixes

cfgresources/cfgresources.go, devices/interfaces.go, providers/dell/idrac8/configure.go, providers/dell/idrac9/configure.go, providers/dell/m1000e/configure.go, providers/dummy/ibmc/configure.go, providers/hp/c7000/configure.go, providers/hp/ilo/configure.go, providers/hp/ilo/helpers.go, providers/hp/ilo/model.go, providers/hp/ilo/query.go, providers/supermicro/supermicrox10/configure.go
Adds network configuration support for ILO4/5
=> Ilo network config

README.md, internal/httpclient/httpclient.go, logging/logging.go, providers/dell/idrac8/idrac8.go, providers/dell/idrac9/idrac9.go, providers/dell/idrac9/redfish_helpers.go, providers/dell/idrac9/setupConnections.go, providers/dell/m1000e/configure.go, providers/hp/c7000/setupConnections.go, providers/hp/ilo/ilo.go, providers/hp/ilo/setupConnection.go, providers/supermicro/supermicrox10/setupConnection.go, providers/supermicro/supermicrox10/supermicrox10.go
Make possible to choose on debug and trace levels
=> Improve logging

providers/dell/idrac8/actions.go, providers/dell/idrac9/actions.go, providers/hp/c7000/actions.go
for hp, try to catch another message
=> file was missing for dell bmc update

providers/supermicro/supermicro.go, providers/supermicro/supermicrox10/supermicrox10.go
work with both. Also fixing the bug #107
=> New supermicro firmware changed the data structure, so I will make it

providers/supermicro/supermicrox/configure.go
This enables maintenance alerts on the supermicro when configuring syslog or we don't get any messages.
=> supermicrox: enable maintenance alerts on syslog configure

discover/probe.go, providers/dell/idrac8/helpers.go
PowerEdge R630
```
[atrubachev@bkbuild-203 ~]$ ./bmcbutler configure --ignorelocation --servers --ips 10.221.174.102
...
{"IPAddress":"10.221.174.102","Model":"idrac8","Serial":"xxxxxxx","Vendor":"Dell","applied":"user, syslog, network, ntp, ldap, ldap_group, https_cert","level":"info","msg":"BMC configuration actions successful.","success":true,"time":"2020-04-20T10:39:16Z"}
...
[atrubachev@bkbuild-203 ~]$
```
PowerEdge R640
```
[atrubachev@bkbuild-203 ~]$ ./bmcbutler configure --ignorelocation --servers --ips 10.193.244.166
...
{"IPAddress":"10.193.244.166","Model":"idrac9","Serial":"yyyyyyy","Vendor":"Dell","applied":"user, syslog, network, ntp, ldap, ldap_group, bios, https_cert","level":"info","msg":"BMC configuration actions successful.","success":true,"time":"2020-04-20T10:49:21Z"} …
```
=> PSM-2318 Add support for Dell PowerEdge R630 (idrac8) / R640 (idrac9)

discover/discover.go, discover/discovery_test.go
Add a functional options that parametrize and/or retrieve per callback a
hint for the most recent successful probe to use.  That hint is a
predefined string constant that points to a specific connect probe.  If
the persisted hint gets out of sync with the implementation or if the
machine behind the coordinate that is probed changes to a different
model, the hinting just makes the probing sub-optimal (hint to a
non-matching probe) or reverts to default behaviour (hint does not match
any probe).
The testing is cleaned up and uses a test case table with parallelized
subtests.  Reflection became necessary, because type assertions are not
parametrizable.  Every mock BMC is tested with no hint, empty hint and
all available hints.
=> discover: probe hint

.github/workflows/ci.yaml
To more easily enable testing, linting, etc to gate PRs.
=> Add github actions file

discover/probe.go, examples/main.go, providers/dell/idrac9/idrac9.go
This PR will enable discovery of dell PowerEdge R6415 machines using idrac9.
Also, updated `example/main.go` with a little cleaner WithLogger.
=> Add dell poweredge R6415 to probe

go.mod, go.sum, internal/ipmi/ipmi.go, providers/hp/ilo/actions.go, providers/ipmitool/boot_device.go, providers/ipmitool/ipmitool.go, providers/ipmitool/ipmitool_test.go, providers/ipmitool/power.go, providers/ipmitool/reset.go, providers/ipmitool/user.go, providers/supermicro/supermicrox/actions.go, providers/supermicro/supermicrox11/actions.go
Add ipmitool implementation of new design interfaces. power, boot device, bmc reset and user read have been implemented. Added context to internal/ipmi calls.
=> Add ipmitool implementation

discover/discover.go
`discover.ScanAndConnect` fails if the BMC host doesn't have a service to connect to on port 443. The expected behavior is to report an error and try the next provider. This PR will allow for this. Fixes https://github.com/bmc-toolbox/bmclib/issues/158
=> Fix premature probe failure

client_test.go
=> remove creds

client.go, providers/ipmitool/ipmitool.go
Register the ipmitool provider in the client.
=> Registry ipmitool provider:

client.go, client_test.go, providers/ipmitool/ipmitool.go, registry/registry.go
=> Add port to registry/client

client.go, client_test.go, registry/registry.go, registry/registry_test.go
Allows ordering the registries based on a list of preferred protocol types.
=> Add PreferProtocol functionality

client.go
Fix error with number of return values.
=> Fix error with number of return values

client.go, providers/ipmitool/ipmitool.go, registry/registry.go
Update to only run `InitFn` once.
=> Update compatibility checking

bmc/boot_device.go, bmc/connection.go, bmc/power.go, bmc/reset.go, bmc/user.go, client.go
The way these slices were being instantiated and then appended to was leaving a nil entry in the slice.
=> Fix nil entry in slices:

internal/ipmi/ipmi.go
Remove debugging/erroneous print statement.
=> Remove print statement

providers/supermicro/supermicrox11/actions.go
Reverts bmc-toolbox/bmclib#209
=> Revert "Update Supermicro X11 PXE boot command"

bmc/firmware.go, bmc/firmware_test.go, client.go, examples/v2/main.go, providers/asrockrack/asrockrack.go, providers/asrockrack/asrockrack_test.go, providers/asrockrack/helpers.go
Reverts bmc-toolbox/bmclib#208
I intended to merge this into master and not the `asrr` branch
=> Revert "ASRR firmware upload mem consumption fixes"

client.go, client_test.go, providers/dell/idrac9/idrac.go
Adds dell provider interface implementations for user create, read, update and delete functionality.
requires https://github.com/bmc-toolbox/bmclib/pull/215 first
=> dell idrac9 user crud implementation for new interfaces:

providers/goipmi/goipmi.go
make port functional in goipmi provider
=> make port functional in goipmi provider

providers/hp/c7000/configure.go
* Checklist
- The HW model number, product name this change applies to (if applicable)
- The BMC firmware and/or BIOS versions that this change applies to (if applicable)
- Description for changelog/release notes
=> Omar m othman/c7000 users

providers/hp/ilo/ilo.go, providers/hp/ilo/ilo_test.go
* Checklist
- The HW model number, product name this change applies to (if applicable)
- The BMC firmware and/or BIOS versions that this change applies to (if applicable)
- Description for changelog/release notes
=> Omar m othman/binary kilowatts

providers/dell/idrac8/idrac8.go, providers/dell/idrac9/idrac9.go, providers/dell/m1000e/m1000e.go, providers/hp/c7000/c7000.go, providers/hp/ilo/ilo.go, providers/supermicro/supermicrox/supermicrox.go, providers/supermicro/supermicrox11/supermicrox.go
* Checklist
- The HW model number, product name this change applies to (if applicable)
- The BMC firmware and/or BIOS versions that this change applies to (if applicable)
- Description for changelog/release notes
=> Omar m othman/errors must be returned

providers/redfish/redfish.go, providers/redfish/user.go
- Implements user deletion over redfish
- Dell
`github.com/stmcginnis/gofish v0.12.0`
- Description for changelog/release notes
- User deletion over redfish
=> providers/redfish: implement user deletion method

go.mod, go.sum
update registrar package dep which includes a fix for filtering drivers
https://github.com/jacobweinstock/registrar/pull/2
https://github.com/jacobweinstock/registrar/pull/1
=> go.mod, go.sum: update registrar package

.github/mergify.yml
=> mergify: rename config file, purge invalid parameter

examples/v1/create-users/doc.go, examples/v1/create-users/main.go, examples/v1/install-firmware/doc.go, examples/v1/install-firmware/main.go, examples/v1/inventory/doc.go, examples/v1/inventory/main.go, examples/v1/status/doc.go, examples/v1/status/main.go, go.mod, go.sum
* Renamed user creation example
* Fixed create-user to use the CSV-provided values
* ran `go mod tidy`
Signed-off-by: Micah Hausler <mhausler@amazon.com>
```
Updated examples with docs
```
=> Updated examples with docs

providers/asrockrack/asrockrack.go
- Declares UserCreate, UserUpdate features supported by asrockrack provider.
- Asrockrack
```
```
=> providers/asrockrack: declare UserCreate, UserUpdate features

providers/redfish/inventory_collect.go
Fixes redfish based inventory data for CPU clockspeeds, and DIMM sizes.
=> Inventory fixes

providers/dell/idrac8/configure.go, providers/dell/idrac9/configure.go
Dell
iDRAC 8 and 9
```
Added initial support for enabling and disabling SNMP on iDRAC 8 and 9
```
=> SNMP enabling and disabling support for Dell iDRAC8 and 9

go.mod, go.sum, lint.mk, providers/intelamt/intelamt.go
This fixes importing the lastest v2 version.
```
```
=> Fix import issue

README.md
Add documentation around timeouts.
```
```
=> Add documentation around timeouts.

internal/ipmi/ipmi.go
When constructing commands executed by ipmitool, the default unspecified cipher suite is cipher suite 3. This PR will default to using the strong cipher suite 17 and defer to the universally supported IPMI 2.0 required cipher suite 3
OpenBMC only supports cipher suite 17 by default while more widely available BMC firmwares support the IPMI 2.0 required cipher suite 3
Tested on ipmitool version: 1.8.18-10
When constructing ipmitool command, will attempt to use cipher suite 17 before using cipher suite 3.
```
```
=> ipmi: Set default cipher suite to 17

README.md, client.go, client_test.go, filter.go, go.mod, go.sum
This enables running single methods with filtering. Improves the filtering UX.
```
```
=> Add one-time filtering functionality:

providers/supermicro/firmware.go
Lists various other SMC X11 range of hardware models as supported.
=> Supermicro x11 supported models

providers/asrockrack/firmware.go, providers/asrockrack/helpers.go
=> Support for Asrockrack e3C256D4ID-NL

client.go, providers/openbmc/firmware.go, providers/openbmc/openbmc.go
Implements Firmware, Inventory, Power related methods for devices running OpenBMC.
=> Add OpenBMC support
