providers/supermicro/supermicrox10/supermicrox10.go
providers/supermicro/supermicrox10/supermicrox10_test.go

update, when calling UpdateCredentials.

supermicrox10: fix bug where credentials in the bmc instance would not

---

providers/dell/idrac8/configure.go

- Set LDAP server port to the one declared in config
- use baseDN declared in config as is, don't prefix 'cn='
- For now disable CA certificate validation, until proper SSL support is implemented.

idrac8: update ldap configuration

---

providers/hp/c7000/xmlhelpers.go

This fixes the panic where the http.Client.Timeout Deadline timer kicks in and causes a panic.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6776b2]
goroutine 15 [running]:
net/http.(*Client).deadline(0x0, 0xc4203de110, 0x0, 0x0)
/usr/lib/go/src/net/http/client.go:189 +0x22
net/http.(*Client).Do(0x0, 0xc420354800, 0xc4204e6a30, 0x1, 0x1)
/usr/lib/go/src/net/http/client.go:500 +0x86
github.com/bmc-toolbox/bmclib/providers/hp/c7000.(*C7000).postXML(0xc420184070, 0xa89040, 0xc4204440b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/jrebello/go/src/github.com/bmc-toolbox/bmclib/providers/hp/c7000/xmlhelpers.go:85 +0x5af

c7000: Add a deadline context to cancel requests that take too long.

---

cfgresources/cfgresources.go
devices/interfaces.go
providers/dell/m1000e/actions.go
providers/hp/c7000/actions.go

This implements support to manage BMC user accounts through the chassis.

c7000: Manage bmc blade users through chassis.

---

devices/interfaces.go
providers/dell/m1000e/configure.go
providers/hp/c7000/actions.go
providers/hp/c7000/configure.go

- Splits out chassis setup configuration methods into its own interface
- Fix c7000 blade user add/mod methods.

Bmc chassis setup interface

---

providers/dell/m1000e/configure.go

We incorrectly returning after configuring just one user.

m1000e: fix User resource not configuring all users (incorrect return)

---

providers/dell/idrac9/configure.go
providers/dell/idrac9/redfish_helpers.go

- Redfish on idrac9's require a valid Accept header
- Check for nil values when retrieving bios settings.

Idrac9 redfish fixes

---

providers/dell/idrac9/configure.go

- default GroupAttributeIsDN to false in LDAP configuration
- and use the full DN for LDAP Role group configuration

idrac9: ldap, ldap group configuration fixes

---

internal/ipmi/ipmi.go

increase ipmitool retransmission to 5s as per Intel recommendation: https://www.intel.com/content/www/us/en/support/articles/000032584/server-products.html
it doesn't hurt

ipmitool: increase retransmission from 1 to 5s

---

devices/interfaces.go
providers/dell/idrac8/configure.go
providers/dell/idrac8/idrac8.go
providers/dell/idrac8/idrac8_test.go
providers/dell/idrac8/query.go
providers/dell/idrac9/configure.go
providers/dell/idrac9/idrac9.go
providers/dell/idrac9/idrac9_test.go
providers/dell/idrac9/query.go
providers/dell/m1000e/configure.go
providers/dell/m1000e/m1000e.go
providers/dell/m1000e/m1000e_test.go
providers/dummy/ibmc/ibmc.go
providers/hp/c7000/c7000.go
providers/hp/c7000/c7000_test.go
providers/hp/c7000/configure.go
providers/hp/ilo/configure.go
providers/hp/ilo/ilo.go
providers/hp/ilo/ilo_test.go
providers/hp/ilo/query.go
providers/hp/ilo/setupConnection.go
providers/supermicro/supermicrox10/configure.go
providers/supermicro/supermicrox10/query.go
providers/supermicro/supermicrox10/supermicrox10.go
providers/supermicro/supermicrox10/supermicrox10_test.go

We have the same set of functions for bmcs and cmcs, but they have different names. I'm making these names standard, so It becomes easy for tool to have generic interfaces for both.

to make simpler to use methods from cmcs and bmcs we are using standard method signatures

---

providers/hp/ilo/configure.go

As part of configuring the user we check if the user_name exists in the BMC,
if it does we POST the action 'mod_user', else we POST with the action 'add_user',
in this fix we check both the user_name, login_name and attempt to configure the account if
either the user_name, login_name match.
We came across an issue where the Administrator username was messed up in the BMC,
this prevented us from being able to make any changes when logged in as the Administrator user,
the account looked like,
{"id":-1145261390,"login_name":"Administrator","user_name":"\u0089d\u0085\u008f\u00a2\u0010\u001e\u000arator"

hp: ilo5 - fix user account exists validation

---

providers/dell/idrac9/idrac9.go

the serial number of the node with the chassis. For all discrete servers
from Dell I've tested it is a realistic statement

We now identify properly if a machine is part of a chassis, by comparing

---

internal/sshclient/sshclient.go

The dell m640s since the new 4.00.00.00 idrac9 release send an empty
challenge once the password has been sent, with change we support the
newer release.

internal/sshclient: Include keyboard-interactive as an auth method

---

cfgresources/cfgresources.go
cfgresources/hp.go
devices/interfaces.go
providers/dell/idrac8/configure.go
providers/dell/idrac9/configure.go
providers/dell/m1000e/configure.go
providers/dummy/ibmc/configure.go
providers/hp/c7000/configure.go
providers/hp/ilo/configure.go
providers/hp/ilo/helpers.go
providers/hp/ilo/model.go
providers/hp/ilo/query.go
providers/supermicro/supermicrox/configure.go

Implement a method of apply power regulator configuration for HPE Gen 8,9,10 - iLO4, iLO5
The configuration that can be used here is,
```
power:
hpe:
regulator: static_high
```    
Where the valid parameters to regulator is one of,
``` 
- static_high
- dynamic
- static_low
- os_control
```

hpe: Add power regulator configuration support

---

providers/dell/idrac8/actions.go
providers/dell/idrac9/actions.go
providers/hp/ilo/actions.go

This fixes the IsOn() method to return false if the host is powered off,
the previous implementation would return an error if the host is powered
off.

Streamline the IsOn() method

---

errors/errors.go
providers/dell/idrac8/actions_test.go
providers/dell/idrac9/actions_test.go
providers/dell/m1000e/actions_test.go
providers/hp/c7000/actions.go
providers/hp/c7000/actions_test.go
providers/hp/ilo/actions_test.go
sshmock/sshmock.go
sshmock/sshmock_test.go

This changes fixes a race condition in tests
Steps to reproduce
```
➜  bmclib git:(master) ✗ go test -count=1 -mod=vendor ./...
?       github.com/bmc-toolbox/bmclib   [no test files]
?       github.com/bmc-toolbox/bmclib/cfgresources      [no test files]
?       github.com/bmc-toolbox/bmclib/devices   [no test files]
ok      github.com/bmc-toolbox/bmclib/discover  0.648s
?       github.com/bmc-toolbox/bmclib/errors    [no test files]
ok      github.com/bmc-toolbox/bmclib/internal/helper   0.227s
?       github.com/bmc-toolbox/bmclib/internal/httpclient       [no test files]
?       github.com/bmc-toolbox/bmclib/internal/ipmi     [no test files]
?       github.com/bmc-toolbox/bmclib/internal/sshclient        [no test files]
?       github.com/bmc-toolbox/bmclib/logging   [no test files]
? …
```

PSM-2320 Fix a race condition in tests

---

internal/sshclient/sshclient.go
internal/sshclient/sshclient_test.go
internal/utils.go
providers/dell/idrac8/actions.go
providers/dell/idrac8/idrac8.go
providers/dell/idrac8/setupConnections.go
providers/dell/idrac9/actions.go
providers/dell/idrac9/idrac9.go
providers/dell/idrac9/setupConnections.go
providers/dell/m1000e/actions.go
providers/dell/m1000e/actions_test.go
providers/dell/m1000e/m1000e.go
providers/dell/m1000e/setupConnections.go
providers/dummy/ibmc/configure.go
providers/hp/c7000/actions.go
providers/hp/c7000/actions_test.go
providers/hp/c7000/c7000.go
providers/hp/c7000/setupConnections.go
providers/hp/ilo/actions.go
providers/hp/ilo/actions_test.go
providers/hp/ilo/ilo.go
providers/hp/ilo/setupConnection.go
sshmock/sshmock_test.go

Before these changes.
A Provider holds an instance of [SSHClient](https://github.com/bmc-toolbox/bmclib/blob/03a62f1096ceb9488df3d2e00f5fc746c37ea08b/internal/sshclient/sshclient.go#L33).
An instance of SSHClient is created in Provider's method [sshLogin()](https://github.com/bmc-toolbox/bmclib/blob/03a62f1096ceb9488df3d2e00f5fc746c37ea08b/providers/dell/idrac8/setupConnections.go#L116). This method is called inside actions (e.g. https://github.com/bmc-toolbox/bmclib/blob/03a62f1096ceb9488df3d2e00f5fc746c37ea08b/providers/dell/idrac8/actions.go#L29).
Because actions can be called in parallel if a race condition happened, there will be created several instances of SSHClient. Each one will create an SSH connection.
This changes:
- separate creation of an instance of SSHClient and creation …

PSM-2322 Fix a race condition in creating SSHClient

---

providers/dell/m1000e/configure.go

We were writing all the users to id=2 and the last write wins.

Fix a bug with managing the users on m1000e chassis

---

providers/supermicro/supermicrox/configure.go

There is a single fmt.Println in the supermicro implementation
that affects structured logs for clients. This PR replaces that with a logged line.

replace single fmt.Println with logger

---

discover/discovery_test.go

I ran into this error while running `go test ./...` -> `fatal error: concurrent map writes`
Calling `viper.SetDefault` in multiple tests happening in parallel seems to be the root. Checking if the value is set before calling `SetDefault` fixes the problem. `go test ./...` will be successful now.

Fix concurrent map writes error

---

discover/probe.go

This PR will fix a dpanic log message thrown from `discover/probe.go#230`.

Fix mismatched number of key/value pairs in log line

---

internal/sshclient/sshclient.go

On iDRAC9 4.22.00.53 ssh started to use keyboard-interactive method
instead of password method (on iDRAC9 4.10.10.10) and answering with
nothing causes the auth to fail.
There is a similar discussion on the forum in:
https://www.dell.com/community/Systems-Management-General/iDRAC8-2-70-70-70-SSH-keyboard-interactive-authentication/td-p/7427565

Handle ssh keyboard-interactive auth

---

discover/probe.go

Enable discovery of Dell PowerEdge R740xd machines using idrac9 so we can interact with them.

Add Dell PowerEdge R740xd to probe

---

providers/dell/idrac9/configure.go
providers/dell/idrac9/idrac9.go

Running probe multiple times exhausts the login
sessions for idrac9 as the idrac.New would open a
session to the idrac but not close it. I moved the
login to Users as this was the original reason to
have the login in New.

Fix idrac9 session exhaustion:

---

internal/utils.go
providers/dell/idrac8/configure.go
providers/dell/idrac8/query.go
providers/dell/idrac9/configure.go
providers/dell/idrac9/query.go
providers/dell/m1000e/configure.go
providers/dell/m1000e/m1000e.go
providers/hp/c7000/configure.go
providers/hp/ilo/configure.go
providers/hp/ilo/query.go
providers/supermicro/supermicrox/configure.go
providers/supermicro/supermicrox/supermicrox.go

There are many places in the code like:
`if err != nil || statusCode != 200 { ... }`
which cause runtime errors because err can be nil then err.Error() is
invoked.
Examples of stacktraces:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb2b9ae]
goroutine 140743 [running]:
github.com/bmc-toolbox/bmclib/providers/hp/ilo.(*Ilo).User(0xc004e56480, 0xc000112580, 0x3, 0x3, 0x1, 0xc005464c30)
bmcbutler/vendor/github.com/bmc-toolbox/bmclib/providers/hp/ilo/configure.go:205 +0xa6e
github.com/bmc-toolbox/bmcbutler/pkg/butler/configure.(*Bmc).Apply(0xc00617f540)
---
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb3007b] …

Avoid crashing while logging if err is nil

---

go.mod
go.sum
registry/registry.go
registry/registry_test.go

Adds the ability to register implementations. `InitRegistry()` returns a generic `interface{}` that will be type asserted or switch(ed) on to convert it to a corresponding concrete interface. The interfaces are mapped to `Feature` types (like `FeaturePowerState`), so implementations can define what functionality they have implemented.

Add registry package

---

client.go
client_test.go

Client package purpose is to be the primary interaction that a bmclib user would use. It interacts with the registry to initialize registered providers with auth and then has pass-through functions to call the interface executor functions.

Add client package

---

client.go
providers/ipmitool/ipmitool.go
registry/registry.go

Client defined logging wasn't making it into provider implementations. This allows the client to define the logger or if not defined by the client we use `logging.DefaultLogger()`.

Add log interface to register function

---

bmc/boot_device.go
bmc/power.go
bmc/reset.go
bmc/user.go

A successful interface method call would return a non-nil error if a previous method call did return an error. This was because we were returning err instead of nil. This PR will fix this bug.

Fix non nil error on success

---

discover/discover.go
discover/probe.go

Found an issue with ScanAndConnect taking over 20 minutes to return if the BMC address wasn't reachable. Context passed into ScanAndConnect wasn't being used for HTTP calls. This commit looks to fix that by using the timeout/cancellation from the passed in user context.

Fix long connection timeout in probes

---

bmc/boot_device.go
bmc/boot_device_test.go
bmc/power.go
bmc/power_test.go
bmc/reset.go
bmc/reset_test.go
bmc/user.go
bmc/user_test.go

If implementations don't or can't handle checking for context timeouts/cancels, this will check for them before each implementation is run in the executor functions.

Add context timeout/cancel checking

---

bmc/connection.go
bmc/connection_test.go
client.go
client_test.go
internal/ipmi/ipmi.go
providers/ipmitool/ipmitool.go
registry/registry.go

implementations that have stateful connections need an open/close method to connect and disconnect. this PR adds theses as main interface methods.
The client package is also updated to handle the open/close functionality. This way multiple calls can all use the same connection(s)/session(s). Another nice thing here is that you can use different registry filters for different calls. For example, if you want to set the next boot using redfish, but get users using ipmitool you can do that. Here's a snippet example, `client_test.go` also has a similar example.
```go
client := NewClient(host, port, user, pass, WithLogger(log))
err := client.Open(ctx)
if err != nil {
panic(err)
}
defer client.Close(ctx)
client.Registry = client.Registry.PreferProtocol("redfish")
ok, err := …
```

Open close interfaces

---

client.go

We were ignoring err when registering providers and we hit a nil pointer error with the `ipmitool` provider when: the `ipmitool` binary is not in the PATH. Excluding providers when their register function fails will solve this and similar future provider registration errors.

fix nil pointer error

---

client.go
client_test.go
providers/ipmitool/ipmitool.go
providers/ipmitool/ipmitool_test.go
registry/registry.go

Fixes https://github.com/bmc-toolbox/bmclib/issues/162. This is an update to `ScanAndDiscover` for the `Client.Registry`. It will run a function (implemented by the provider) to determine if the provider is compatible with the given BMC. This will be done for all registered providers and then it will update the `Client.Registry` with all compatible providers that were discovered.
This (eventually) moves all the `discover/probe.go` functionality into each specific provider.

Add discovery of compatible providers

---

client.go

To fix the [nil pointer error](https://github.com/bmc-toolbox/bmclib/commit/0323a20e87821ba9bd6509b8b122a0b3f8259ba9) that can happen if an error is not checked from a providers `InitFn`, we skip adding the provider to the registry. This should happen in`setProviders`, not in `getProvider`. This way we limit the times we call the `initFn` and `setProviders` already puts the provider interface into the registry so`getProviders` does not need to call `initFn` again to get it, it can just get the interface from the `Registry.ProviderInterface`.

Move provider registration error check

---

discover/discovery_test.go
discover/probe.go
providers/supermicro/supermicrox/configure.go
providers/supermicro/supermicrox/supermicrox.go
providers/supermicro/supermicrox/supermicrox_test.go
providers/supermicro/supermicrox11/supermicrox.go
providers/supermicro/supermicrox11/supermicrox_test.go

fixes https://github.com/bmc-toolbox/bmclib/issues/183
Changed the way Supermicro does probing. We don't only look for `x10` or `x11` when getting the model type. If the call to get the model works, we use it. So If the x11 `HardwareType()` response is not an empty string, meaning that the call to get its model WAS successful, then we use the x11 provider code. Same for the x10 code.  
Also, updated the user mgmt code for x10 because with the existing code If a single user was passed in it would always add/update/delete that user from slot 2 (index 1) on the BMC. This means that if an existing user, say `ADMIN`, was configured there, but I passed in to create a new user, named `TestUser`, then `TestUser` would overwrite `ADMIN`. This PR fixes that and the `ADMIN` user in this example …

Add new smc support

---

discover/probe.go
providers/dell/idrac8/helpers.go

Updated the way we check for available slots in the UI. disabled with a nonempty username should be a candidate for use as idrac8 UI doesn't allow empty usernames.

Add PowerEdge C6320 support

---

go.mod
go.sum

This new version fixes a provider ordering bug in the registrar's `FilterForCompatible` function.

Update registrar version

---

client.go

Fixes issue where a passed in registry to `NewClient` was being overwritten by default values.

Fix overwriting passed in Registry:

---

client.go

fix for broken `NewClient` in v0.4.9.
In `NewClient`, calling `defaultClient.registerProviders()` before setting the `host`, `port`, `user`, and `pass` causes registering providers to not have `host`, `port`, `user`, and `pass` set and results in cascading errors.

Fix nil values in provider registration:

---

providers/ipmitool/ipmitool.go
providers/ipmitool/ipmitool_test.go

Checking if a machine is on for the compatibility check will cause the check to fail if the BMC is up, is compatible, but the host machine is powered off. Just checking if a power state call returned successfully should allow the check to be more accurate and work even if the host machine is off.

Update ipmi provider IsCompatible Func

---

devices/interfaces.go
examples/main.go
providers/dell/idrac8/setupConnections.go
providers/dell/idrac9/setupConnections.go
providers/dummy/ibmc/ibmc.go
providers/hp/ilo/setupConnection.go
providers/supermicro/supermicrox/setupConnection.go
providers/supermicro/supermicrox11/setupConnection.go

This enables the existing codebase to be implemented by both the current
and newer interfaces.
the current interface (bmclib v0)
https://github.com/bmc-toolbox/bmclib/blob/c1fed9df833628df57796245d085c97187f06f9a/devices/interfaces.go
the newer interface (bmclib v2)
https://github.com/bmc-toolbox/bmclib/blob/c1fed9df833628df57796245d085c97187f06f9a/bmc/connection.go#L17

Add context parameter to Close()

---

providers/supermicro/supermicrox11/actions.go

The difference between the 2 commands is `chassis bootdev pxe` vs
`chassis bootdev pxe options=efiboot`. The one with options=efiboot does
not really work (if the server has OS installed on disk, it will boot
it).
Tested on Supermicro X11DSC+ with BIOS 3.1 and firmware 1.68.

Update Supermicro X11 PXE boot command

---

bmc/bmc.go
bmc/boot_device.go
bmc/boot_device_test.go
bmc/connection.go
bmc/connection_test.go
bmc/power.go
bmc/power_test.go
bmc/provider.go
bmc/reset.go
bmc/reset_test.go
bmc/user.go
bmc/user_test.go
client.go
client_test.go
go.mod
go.sum
providers/ipmitool/ipmitool.go

Without breaking clients, this adds the capability of relaying to the end-user metadata about the method call, like the name of the provider that successfully executed. This gives info back to end-users to help if they need to use a certain provider for certain hardware, for other determinations that only happen on the end-user side, for troubleshooting, and removes some of the mystery around what happens when a method is called.
addresses https://github.com/bmc-toolbox/bmclib/issues/210
example usage in [`client_test.go`](https://github.com/bmc-toolbox/bmclib/pull/212/files#diff-4dc56e64f310cd8c12bb00f75c09e83f5d875563ea9901788e525487dc6788b3)

Identify the provider that executed successfully:

---

providers/asrockrack/asrockrack.go

since its easily out of date after a firmware update

providers/asrockrack: lets not 'cache' and return firmware version data

---

discover/discover.go

Both the "order" and the "devices" arrays must be equal in length, because of
for _, probeID := range order {
probeDevice := devices[probeID]
bmcConnection, err := probeDevice(opts.Context, opts.Logger) // Boom!
}

fix nil reference exception in device probe

---

bmc/bmc.go
bmc/boot_device.go
bmc/boot_device_test.go
bmc/connection.go
bmc/connection_test.go
bmc/power.go
bmc/power_test.go
bmc/provider.go
bmc/reset.go
bmc/reset_test.go
bmc/user.go
bmc/user_test.go
client.go
client_test.go

Current:
```go
state, err := client.GetPowerState(ctx, &metadata)
if err != nil {
panic(err)
}
fmt.Println(state)
fmt.Printf("metadata:  %+v\n", metadata)
```
Proposed:
```go
state, err := client.GetPowerState(ctx)
if err != nil {
panic(err)
}
fmt.Println(state)
fmt.Printf("metadata: %+v\n", client.GetMetadata())
```
After using the metadata for a little, I don't like the
experience. Having to pass in metadata was not easily
understood and was trying to be too clever. This update
will make metadata available for all methods. the user just
has to call GetMetadata() to retrieve it.
Public API is affected as the client will no longer be able
to pass in the &metadata var. Seeing as we are not v1,
I feel comfortable proposing this change.
Signed-off-by: Jacob Weinstock …

Update metadata user experience:

---

internal/ipmi/ipmi.go
providers/ipmitool/ipmitool.go

Power off in ipmitool was duplicating the internal ipmi
package functionality in PowerOff but doing it poorly.
Specifically not checking for an error when calling `IsOn`.
Also, the internal ipmi package `PowerOn` has been updated.
It now follows how ipmitool behaves when calling `chassis power on`.
ipmitool will return an exit code of 0 if calling `chassis power on`
against a machine in a powered-on state.

Fix bug in provider ipmitool:

---

providers/asrockrack/asrockrack.go

the BMC resets a few seconds after an update, we increase the flash progress check interval 
and reduce the flash timeout value, since 30 minutes is way too long - a BMC/BIOS flash takes a max of 10 minutes.

providers/asrockrack: update flash progress and check interval timeouts

---

client.go
client_test.go
examples/v1/main.go

The UX feels unnecessarily verbose/explicit. Most other
libraries that have open/close methods just return an error.
These libraries dont return multiple implementation but with
the ability to get metadata for each Client.X call I dont
think we need to worry about making it that explicit that
we've modified the providers. Open for discussion here, but
putting this in as a PR regardless.
Signed-off-by: Jacob Weinstock <jakobweinstock@gmail.com>

Update Client.Open method:

---

client.go

If a user doesn't provide a logger our current default logger will still log. This feels like the wrong user experience. If a client doesn't pass in a logger we shouldn't log either. This makes that happen. This only affects the new interfaces and users that use `bmc.NewClient`

Update default logging for Client:

---

providers/dell/idrac9/idrac.go

implement Provider interface. this means `Client.GetMetadata` will have the provider-defined name instead of the provider's type.

implement Provider interface

---

providers/supermicro/supermicrox/query.go
providers/supermicro/supermicrox/supermicrox.go
providers/supermicro/supermicrox/supermicrox_test.go

I had a problem with one of the servers where the XML API was returning the wrong chassis serial number despite DMI and FRU both pointing at the correct chassis serial number. So, I decided to switch to RedFish for that.

Using RedFish for chassis detection for SuperMicro servers.

---

client.go

This fixes a poor user experience of panicking on calls to metadata if the metadata is nil.

Fix panic for nil metadata:

---

internal/ipmi/ipmi.go
providers/hp/ilo/actions.go
providers/supermicro/supermicrox/actions.go
providers/supermicro/supermicrox11/actions.go

Without this change, we get "Set Chassis Power Control to Cycle failed: Command not supported in present state" if the chassis is turned off.

Bug! We have to make sure that the chassis is on before power cycling!

---

internal/ipmi/ipmi.go

The current behavior in `internal/ipmitool` is to error if a request for a power-off is called against an already powered-off machine. I proposed we remove this behavior and if a request for a power-off (in `internal/ipmitool`) is called against an already powered-off machine we return success. This also mirrors `ipmitool` itself. It does not error out when an already-off machine calls power off against it.
* Checklist
- The HW model number, product name this change applies to (if applicable)
- The BMC firmware and/or BIOS versions that this change applies to (if applicable)
- Description …

Don't error on ipmitool power off when machine is already off:

---

.github/workflows/ci.yaml

Signed-off-by: Micah Hausler <mhausler@amazon.com>
* Checklist
Enables verbose output for failing golangci-lint

Set verbose output to golangci-lint

---

providers/ipmitool/ipmitool.go

This keeps the `Open` behaviour consistent with the other providers,
such that the provider is excluded if Open() fails.

providers/ipmitool: Open() should attempt to connect

---

errors/errors.go
providers/dell/idrac9/idrac.go
providers/ipmitool/ipmitool.go
providers/redfish/redfish.go

compatibility check logs to log only when debug/trace logging is
enabled, a lot of compatibility checks are performed for each
connection.

errors: less verbose compatibility check errors

---

providers/redfish/firmware.go

Includes the `downloaded` state for firmware install.

redfish/firmware: downloaded is another firmware install state returned by idracs

---

providers/redfish/tasks.go

This registers a few more Dell component update task names, these task names are used to identify firmware updates in progress.
- Dell

redfish/dell tasks: register task names for NIC, Drive, controllers

---

.golangci.yml
go.mod
go.sum
providers/redfish/tasks.go

This registers a few more Dell component update task names, these task names are used to identify firmware updates in progress.
same as https://github.com/bmc-toolbox/bmclib/pull/282, except for bmclib v0

[v0] dell redfish tasks 

---

cfgresources/cfgresources.go
providers/hp/ilo/configure.go
providers/hp/ilo/helpers.go
providers/hp/ilo/model.go

HP
-
iLO4 and 5
-
```
Added initial SNMP support to enable and disable SNMP.
New configuration setting added to indicate enabling or disabling SNMP. Sample config available on [bmcbutler](https://github.com/bmc-toolbox/bmcbutler/blob/2073ba74749452ffa50e607fa193713541cb9ab1/samples/cfg/configuration.yml)
```

Initial HP SNMP support

---

providers/hp/ilo/configure.go
providers/hp/ilo/ilo.go

Starting from ILO 5 2.55 Support import of SSL certificate which is more than 20KB is allowed via redfish endpoints 
https://support.hpe.com/connect/s/softwaredetails?softwareId=MTX_5db4ea82a110436daf58edbc61&language=en_US&tab=revisionHistory 
HPE
HPE ILO 5 v2.55 and higher
```
```

HP Certificate Upload via redfish endpoint

---

discover/probe.go

Currenlty we have noticed that hpC7000s that have only one OA takes more than 60s seconds to generate the XML Data via https://<Ip>/xmldata?item=all. Increasing the timeout to 120 seconds to accomodate such chassis. Other "healthy chassis" scan will not be affected by this change as it will return success as soon as the XML is generated. 
It might however cause dead chassis to create a delay, which I assume is tolerable damage in return of saving half alive chanssis :) 
- [ NA] Tests added
- [ Y] Similar commits squashed
HP
HPC7000
N/A
vendor specific
```
```

Chassis with single OA takes more than 60 seconds

---

errors/errors.go
go.mod
go.sum
internal/utils.go
providers/redfish/firmware.go
providers/redfish/firmware_test.go
providers/redfish/inventory.go
providers/redfish/inventory_collect.go
providers/redfish/redfish.go
providers/redfish/redfish_test.go
providers/redfish/tasks.go
providers/redfish/user.go

- Fixes various superfluous nil error checks and remove calls to deprecated ioutil package.
- Adds a check to ensure a Redfish session is active, this prevents the clients from seeing panics (see paste below)
when a redfish session was closed or was not previously created.
- A few inventory fixes.
Related: https://github.com/stmcginnis/gofish/pull/214
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17b78fc]
goroutine 30 [running]:
github.com/bmc-toolbox/bmclib/v2/providers/redfish.(*Conn).status(0x17cb315?, {0xc0002f6470?, 0x0?})
/go/pkg/mod/github.com/bmc-toolbox/bmclib/v2@v2.0.0/providers/redfish/redfish.go:236 +0x1c
github.com/bmc-toolbox/bmclib/v2/providers/redfish.(*Conn).PowerStateGet(0x18768c …
```

Redfish session fixes

---

.github/mergify.yml
go.mod
go.sum
providers/intelamt/intelamt.go
providers/intelamt/intelamt_test.go

The Go module of my fork of github.com/ammmze/wsman has been updated to github.com/jacobweinstock/wsman
This will allow imports of this to not have to specify replace directives in go.mod. The hope is that the upstream will accept the context changes and this won't be necessary.
Fixes #295 
```
```

Use renamed module for go-amt

---

client.go
internal/redfishwrapper/client.go
internal/redfishwrapper/power.go
internal/redfishwrapper/system.go
providers/asrockrack/helpers.go
providers/asrockrack/mock_test.go
providers/ipmitool/ipmitool_test.go
providers/redfish/firmware.go
providers/redfish/inventory.go
providers/redfish/inventory_collect.go
providers/redfish/main_test.go
providers/redfish/redfish.go
providers/redfish/tasks.go
providers/redfish/user.go

This is based on the feedback in https://github.com/bmc-toolbox/bmclib/pull/291
This moves the redfish client wrapping outside of the providers/redfish
package, these methods always check the redfish session is valid before
calling into the wrapped redfish library - gofish.
By moving this out, other providers can also import the redfishwrapper.

Redfish refactor

---

providers/redfish/inventory.go
providers/redfish/inventory_collect.go
providers/redfish/redfish.go

Updates the Redfish provider inventory collection to work on Supermicro hardware,
[6029P-E1CR12L.json](https://gist.github.com/ca3232eb15552298e2b5558b6c387065)
[SYS-5019C-MR.json](https://gist.github.com/481e68f6687ae92180887f9864f4ec71)
[SYS-510T-MR.json](https://gist.github.com/71f35d7a9630428cd4947eedee74e1d3) 
- [X ] Similar commits squashed
Supermicro
Should work with all SMC hardware, tested on hardware variants,
SYS-5019C-MR
6029P-E1CR12L
SYS-510T-MR
```
Redfish inventory support for Supermicro hardware.
```

Supermicro redfish inventory support

---

providers/intelamt/intelamt.go

This fixes a panic in the bmclib client init when calling `FilterForCompatible()` on the registered drivers.
```
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x174ca88]
goroutine 126 [running]:
github.com/jacobweinstock/go-amt.getPowerStatus({0x1c3ccf8, 0xc00057a270}, 0xc0001c6d20?)
/Users/jrebello/go/pkg/mod/github.com/jacobweinstock/go-amt@v0.0.0-20221125040441-53475f4ae023/power.go:50 +0x28
github.com/jacobweinstock/go-amt.isPoweredOn({0x1c3ccf8?, 0xc00057a270?}, 0x0)
/Users/jrebello/go/pkg/mod/github.com/jacobweinstock/go-amt@v0.0.0-20221125040441-53475f4ae023/power.go:140 +0x28
github.com/jacobweinstock/go-amt.(*Client).IsPoweredOn(0x1c36a20?, {0x1c3ccf8?, 0xc00057a270?}) …
```

fix panic in FilterForCompatible()

---

providers/intelamt/intelamt.go
providers/intelamt/intelamt_test.go

Panics were happening because of not handling return errors from `amt.NewClient`.
Intel AMT
Fix IntelAMT provider panics.
```
```

Rework intel amt provider to not panic:

---

internal/redfishwrapper/boot_device.go
providers/redfish/redfish.go

This PR enables setting the boot device for redfish systems. Where applicable, it uses the same strings as ipmitool to maintain compatibility. (For example, ipmitool expects "disk" whereas redfish expects "Hdd".)
```
Redfish set boot device support.
```

Add redfish BootDeviceSet support

---

README.md
client.go
client_test.go
examples/inventory/main.go
go.mod
go.sum
internal/redfishwrapper/client.go
internal/redfishwrapper/client_test.go
providers/redfish/redfish.go

This enables the client to optionally define Redfish versions its not compatible
with, giving the user the option to ignore the Redfish endpoint on BMCs
for cases where the Redfish version is too old or is known to not have an expected functionality.
```
- Adds the incompatible Redfish versions option parameter. 
```

Redfish versions param

---

bmc/virtual_media.go
bmc/virtual_media_test.go
client.go
internal/redfishwrapper/virtual_media.go
providers/providers.go
providers/redfish/redfish.go

This PR adds support for setting redfish virtual media. It can be used, for instance, to specify the URL of an ISO image that the machine should boot from.
Redfish. Tested on a Dell R640 server.
```
Added Redfish VirtualMedia support
```

Support redfish VirtualMedia

---

go.mod
go.sum
providers/redfish/inventory_collect.go
providers/redfish/inventory_collect_test.go

Reworked according to discussion in https://github.com/bmc-toolbox/bmclib/pull/308.
Multiple ports in the same network adapter are now inventoried as different NICPorts under the same NIC.
Added some network port fields.
Fixed network speed conversion.
Added unit tests for network port and ethernet interface processing.
```
Added support for NICs with multiple ports.
Fixed network speed conversion.
```

redfish: added support for adapters with multiple ports

---

bmc/connection.go
bmc/connection_test.go
client.go
client_test.go
providers/intelamt/intelamt.go

Wraps the Intel AMT provider connection setup to return on context deadline.
Adds a connection timeout parameter for opening connection,
As of now, a user may choose to pass in a context deadline into the bmclib client, which
is shared between all the [bmclib providers](https://github.com/bmc-toolbox/bmclib/blob/main/client.go#L115) that is - when creating an a new connection/session on a BMC.
The shared timeout value entails that a single provider can attempt to connect for the the whole timeout deadline, and so leaving the other providers (which may be the successful ones) with much lesser time to connect and carry out their operation.
The `WithConnectTimeout()` client option sets the timeout when connecting to a BMC to create a new session.
When not defined the deadline value passed in …

Connection timeouts

---

bmc/boot_device.go
bmc/boot_device_test.go
bmc/connection.go
bmc/connection_test.go
bmc/firmware.go
bmc/inventory.go
bmc/postcode.go
bmc/power.go
bmc/power_test.go
bmc/reset.go
bmc/reset_test.go
bmc/user.go
bmc/user_test.go
bmc/virtual_media.go
bmc/virtual_media_test.go
client.go
client_test.go
providers/asrockrack/asrockrack.go

This expands the timeout for opening connections to all method/BMC interactions.
If a context with a timeout IS provided to a method call but no per provider timeout is defined, then we default to a timeout of the provided timeout duration divided by the number of providers/drivers in the Client.Registry.Drivers slice.
If a context with a timeout IS NOT provided to a method call and no per provider timeout is defined, then we use the defaultConnectTimeout of 30 seconds.
```
```

Add timeouts everywhere

---

errors/errors.go
providers/redfish/bios.go

Fixes a nil panic in Redfish BIOS data queries.
- The redfish mock code could use some work so that tests can check for non-happy cases, at the moment its not trivial to implement tests for those conditions.

providers/redfish: fixes a panic in cases where a nil bios object was returned

---

Makefile

When invoking `make` its not ideal to run a linter. This change ensures the `help` target is executed instead.

Make help command default make target

---

internal/redfishwrapper/client.go

fixes a panic on `Close()` in the Redfish provider if the Redfish client was never setup.
```
goroutine 37 [running]:
github.com/bmc-toolbox/bmclib/v2/internal/redfishwrapper.(*Client).Close(...)
/Users/jrebello/go/pkg/mod/github.com/bmc-toolbox/bmclib/v2@v2.0.1-0.20230324092939-d39fb75b6aa9/internal/redfishwrapper/client.go:126
github.com/bmc-toolbox/bmclib/v2/providers/redfish.(*Conn).Close(0x0?, {0x100c00005a804?, 0x477d9e?})
/Users/jrebello/go/pkg/mod/github.com/bmc-toolbox/bmclib/v2@v2.0.1-0.20230324092939-d39fb75b6aa9/providers/redfish/redfish.go:63 +0x20
github.com/bmc-toolbox/bmclib/v2/bmc.closeConnection({0x107cd78, 0xc000182660}, {0xc0002de280?, 0x2, 0x0?})
```
```
```

redfish: fix nil check on gofish client

---

client.go
client_test.go
examples/status/main.go
internal/redfishwrapper/client.go
internal/redfishwrapper/client_test.go

Implements client option to enable Basic Auth on the Gofish redfish driver
fixes #328

Sets basic auth on the gofish driver

---

client.go
client_test.go

This was erroring with `cmp.Diff` complaining about comparing `logr`. I retested again and this is not needed at all.
```
```

Remove union in .FilterForCompatible:

---

go.mod
go.sum

The upgraded `github.com/jacobweinstock/registrar` dep has a fix for keeping the registry ordered properly when calling `FilterForCompatible`.
```
```

Upgrade registrar dependency:

---

bmc/screenshot.go
bmc/screenshot_test.go
client.go
errors/errors.go
examples/screenshot/doc.go
examples/screenshot/main.go
internal/redfishwrapper/client.go
option.go
providers/dell/fixtures/serviceroot.json
providers/dell/idrac.go
providers/dell/idrac_test.go
providers/providers.go

Implements screenshot capture feature for Dell IDracs.
Dell
```
- Screenshot feature for Dell Idracs
```

Implements screenshot feature for dell

---

bmc/bmc.go
bmc/boot_device.go
bmc/connection.go
bmc/power.go
client_test.go

This adds the error message for failed method calls per providers to metadata. These erorrs were previously not accessible. These errors are captured in metadata regardless of whether the method returns successful or not. This is helpful in debugging providers that error but the method call succeeds. This doesn't change the behavior of any methods. After each method call metadata can be interrogated for error messages of any failed providers.
The example metadata below shows that while the open method call succeeded for ipmitool, dell, and gofish it did not succeed for IntelAMT and asrockrack. We now have access to the error messages for those failed one.
```
{
SuccessfulProvider:""
ProvidersAttempted:[ipmitool asrockrack gofish IntelAMT dell]
SuccessfulOpenConns:[ipmitool dell gofish] …
```

Add metadata field for error messages:

---

providers/supermicro/firmware_bios.go
providers/supermicro/firmware_bmc.go
providers/supermicro/firmware_bmc_test.go
providers/supermicro/supermicro.go
providers/supermicro/supermicro_test.go

support firmware installs on BMCs running firmware <= 1.23.06
The older firmware expects Host headers to be in a certain format (without the port) and it expects a Referrer header. The firmware upload endpoint expects the multipart header slightly different as well.
Tested this change works on the newer firmware (1.74.x) as well.
- SMC X11s
```
- Support for SMC firmware updates on BMCs running firmware <=1.23.06
```

supermicro/firmware: support firmware installs on BMCs running older firmware

---

internal/redfishwrapper/client.go
providers/redfish/firmware.go
providers/redfish/firmware_test.go
providers/supermicro/firmware.go

- Adds a remaining timeout check on the Redfish provider `FirmwareInstall` method.
- Overrides the Redfish wrapper HTTP client timeout for the `FirmwareInstall` method.
The Redfish wrapper client - Gofish has a context timeout on the HTTP client set when `Open()` is invoked, this timeout value is often insufficient for the `FirmwareInstall` method to complete successfully, and so the `FirmwareInstall` method overrides this timeout value and restores it when done.  
```
- Require a higher context timeout value before proceeding with FirmwareInstall.
- Set http client timeout to the one passed in through the context to FirmwareInstall.
```

Redfish override timeout for FirmwareInstall

---

examples/install-firmware/main.go
providers/redfish/firmware.go
providers/redfish/firmware_test.go

The Redfish provider currently reads the firmware files into memory before a multipart upload,
this results in high memory consumption for the client and can be problematic for cases
where firmware installs have to be performed simultaneously.
This change was part of bmclib v1 https://github.com/bmc-toolbox/bmclib/pull/279 
but was somehow missed from being included in v2.
Tested with Dell R6515's, R7640.
heap profile - with streaming uploads
```
(pprof) top 20
Showing nodes accounting for 2059.99kB, 100% of 2059.99kB total
Showing top 20 nodes out of 29
flat  flat%   sum%        cum   cum%
520.04kB 25.24% 25.24%  1034.42kB 50.21%  encoding/json.(*Decoder).refill
514.38kB 24.97% 50.21%   514.38kB 24.97%  compress/flate.NewReader
513.56kB 24.93% 75.15%   513.56kB 24.93%  regexp/syntax.init …
```

Redfish stream multipart uploads

---

examples/rpc/main.go
providers/rpc/http_test.go
providers/rpc/logging.go
providers/rpc/payload.go
providers/rpc/rpc.go
providers/rpc/rpc_test.go

The request body was being dropped after the io.Copy causing issues with further reading of it. Add a PingMethod for the Open call. This way we send something for the client to interpret instead of nothing. Update tests.
```
```

Fix copying of request body:

---

providers/rpc/http.go
providers/rpc/rpc_test.go

In testing this was causing issues with consumers of the provider using the error string. Also, for security reasons we might not want to return an arbitrary response body, especially when it doesn't conform to the response contract.
```
```

Remove returning the response body:

---

providers/redfish/tasks.go
providers/redfish/tasks_test.go

providers/redfish/tasks: returns TaskNotFound on 404

---

client.go
option.go
providers/redfish/redfish.go

- Exposes the Redfish Etag match header disable parameter added in https://github.com/bmc-toolbox/bmclib/pull/353
- Minor refactor - move provider registration into individual methods
```
```

Client opts fixes

---

client.go
providers/rpc/rpc.go

This plumbs through either the default or user-supplied http client to the RPC provider.
```
```

User supplied http client in RPC provider:

---

providers/dell/fixtures/systems_embedded_no_manufacturer.1.json
providers/dell/fixtures/systems_embedded_not_dell.1.json
providers/dell/idrac.go
providers/dell/idrac_test.go

This was leaving open sessions in non Dell machines. Closed sessions when the Dell Open function returns error after successfully opening.
```
```

Fix session leak in Dell provider:

---

providers/asrockrack/firmware.go
providers/asrockrack/helpers.go
providers/asrockrack/mock_test.go

By default, update is broken on e3c256d4i. This PR fixes it. Compatibility with e3c246d4i needs to be tested

e3c256d4i support

---

bmc/floppy.go
bmc/floppy_test.go
client.go
examples/floppy-image/doc.go
examples/floppy-image/main.go
internal/redfishwrapper/virtual_media.go
providers/providers.go
providers/supermicro/floppy.go
providers/supermicro/supermicro.go

Defines and implements the floppy upload and unmount feature for Supermicro X11, X12 BMCs.
This enables uploading a floppy image onto the BMC, which can then be used to boot off the image.
This differs from mounting remote images as virtual media, which can timeout over time.
-  Supermicro
- X11, X12

Floppy upload and unmount

---

providers/asrockrack/firmware.go

Check component with upper case version (as slugs are upper case in common lib)
asrockrack

providers/asrockrack: when checking component, use upper case

---

providers/supermicro/firmware.go
providers/supermicro/floppy.go
providers/supermicro/supermicro.go
providers/supermicro/supermicro_test.go
providers/supermicro/x11_firmware_bios.go
providers/supermicro/x11_firmware_bmc.go

Supermicro X11s running on older firmware don't have CSRF support and this change removes the requirement to have a CSRF token so firmware can be updated on those devices.
- [] Tests added
Supermicro X11s running BMC firmware `01.71.11 10/25/2019` and older
X11DPH-T

Supermicro no CSRF

---

bmc/firmware.go
bmc/firmware_test.go
client.go
constants/constants.go
internal/redfishwrapper/task.go
internal/redfishwrapper/task_test.go
providers/supermicro/firmware.go
providers/supermicro/supermicro.go
providers/supermicro/x11.go
providers/supermicro/x11_firmware_bios.go
providers/supermicro/x11_firmware_bmc.go
providers/supermicro/x11_firmware_bmc_test.go
providers/supermicro/x12.go

Updates the `FirmwareTaskVerifier` interface and its implementations to return a `constant.TaskState` type.

Taskstate constant

---

constants/constants.go
errors/errors.go
providers/asrockrack/asrockrack.go
providers/asrockrack/asrockrack_test.go
providers/asrockrack/firmware.go
providers/asrockrack/helpers.go
providers/asrockrack/helpers_test.go
providers/asrockrack/inventory.go
providers/asrockrack/inventory_test.go
providers/asrockrack/mock_test.go
providers/asrockrack/power.go

Reworks the Asrockrack provider to to use the newer bmclib client firmware interfaces
along with a few fixes for inventory collection and firmware install status lookup.
tested on `E3C256D4ID-NL`, `E3C246D4I-NL`
Asrockrack
- E3C256D4ID-NL
- E3C246D4ID-NL
- E3C246D4I-NL

Asrockrack firmware support

---

providers/openbmc/openbmc.go
providers/supermicro/supermicro.go

This makes sure when the provider is pinned/filtered* the BmcReset method is available.
* https://github.com/bmc-toolbox/bmclib#one-time-filtering
OpenBMC firmware, Supermicros

openbmc, supermicro: implement BMCResetter interface

---

bmc/sol.go
bmc/sol_test.go
client.go
internal/ipmi/ipmi.go
providers/ipmitool/ipmitool.go
providers/ipmitool/ipmitool_test.go
providers/providers.go

A new operation to terminate an active SOL session.
```
A new `TerminateSOL` operation, via the ipmitool provider, can be used to terminate an active SOL session.
```

Add TerminateSOL method

---

providers/openbmc/openbmc.go

Returning the error will ensure the provider is removed from future calls.
```
```

[OpenBMC] Return err if open fails:

---

bmc/nmi.go
bmc/nmi_test.go
client.go
internal/ipmi/ipmi.go
internal/redfishwrapper/power.go
providers/dell/idrac.go
providers/ipmitool/ipmitool.go
providers/ipmitool/ipmitool_test.go
providers/openbmc/openbmc.go
providers/redfish/redfish.go
providers/supermicro/supermicro.go

Support for sending an NMI has been added to ipmi, redfish, redfishwrapper, and all providers that use the redfishwrapper.
```
Adds support for sending an NMI to ipmi, redfish, redfishwrapper, and all providers that use the redfishwrapper.
```

Add support for sending NMI

---

providers/supermicro/x12.go

Support BIOS firmware updates on X12SPO-NTF
verified changes work with both BIOS and BMC updates on the hardware.
SMC
X12SPO-NTF

supermicro/x12: support BIOS firmware updates on X12SPO-NTF

---

providers/supermicro/firmware.go

This fixes a regression introduced by a rework on the provider, which would cause this error to be returned,
`supermicro: expected an firmware upload taskID`

supermicro/x11: lower case device model before comparison

---

README.md
go.mod
go.sum

We don't seem to have an official strategy for the Go version in go.mod. I believe that, as a library, we should only bump this version if there are dependencies we use that would require us to move to this version ([ref](https://go.dev/doc/modules/gomod-ref#:~:text=The%20minimum%20version%20of%20Go%20required%20by%20the%20current%20module.)). I don't believe that we have any dependencies that warrant a bump. Bumping this version will require user to update to this version. While it is a good practice to build with the latest version of Go, this requirement will be making a decision for users that should be theirs and not ours. We are a library not a binary to be built. In this aspect, we are using the version in go.mod incorrectly, in my opinion, by doing this. This assumes we don't have …

Revert to Go 1.18 in go.mod and make policy around this official

---

go.mod
go.sum
internal/executor/executor.go
internal/executor/executor_test.go
internal/sum/sum.go

This PR removes currently unused interface functions from the Executor interface.
```
* Removed currently unused interface functions from the Executor interface
```

Slim down the Executor interface

---

examples/virtualmedia/doc.go
examples/virtualmedia/main.go
internal/redfishwrapper/virtual_media.go

At least one BMC, Supermicro X11SDV-4C-TLN2F, did not support setting `inserted` and/or `writeProtected` in the payload properties in redfish calls to do a virtual media mount. This falls back to not using them if the initial call with them in the properties fails.
This was test and worked successfully on a Supermicro (X11SDV-4C-TLN2F), HP ILO5, and Dell iDRAC9.
```
```

Update virtual media mounting:

---

internal/redfishwrapper/firmware.go

In contrast to other server-vendors, SMC does not return the task id in the Location header of the response to a firmware upload. In BMC version 1.05.03 (Redfish version 1.14.0) the payload format changes from a TaskAccepted message to a Redfish task, which breaks task id detection. This change adds an attempt to deserialize the task structure before falling back to the earlier TaskAccepted message type.
This also corrects the startUpdateURI.

expand response payload processing

---

internal/redfishwrapper/boot_device.go
internal/redfishwrapper/power.go
internal/redfishwrapper/system.go
internal/redfishwrapper/virtual_media.go

Add system name matching to Managers and make sure redfish methods use the Systems helper method.
```
```

Update redfish system name matching

---

providers/supermicro/firmware_bios_test.go
providers/supermicro/supermicro.go
providers/supermicro/x11_firmware_bmc_test.go

A regression crept in recently where the 'sum' client was not being assigned to the 'serviceclient' when the supermicro provider was instantiated.     This change fixes that problem.

providers/supermicro/supermicro.go: Initialize sum 'client' during serviceclient init

---

bmc/bios.go
examples/bios/main.go
providers/supermicro/supermicro.go

Fix example
Fix SetBiosFromFile
Fix the SetBiosFromFile example

Fix SetBiosFromFile

---

internal/redfishwrapper/virtual_media.go

Some redfish implementations will fail to eject media if no media is mounted. The redfish server behavior is to report that the virtual media doesn't support media ejection. So we need to check for this.
```
```

Fix media mounting eject implementation:

---

bmc/bios.go
bmc/boot_device.go
bmc/connection.go
bmc/firmware.go
bmc/floppy.go
bmc/inventory.go
bmc/postcode.go
bmc/power.go
bmc/provider.go
bmc/reset.go
bmc/screenshot.go
bmc/sel.go
bmc/sol.go
bmc/user.go
bmc/virtual_media.go
providers/supermicro/firmware_bios_test.go
providers/supermicro/supermicro.go
providers/supermicro/x11_firmware_bmc_test.go

Fix bug introduced by #402. This PR handles errors properly and adds some nil checking in the `bmc` package. By ignoring an error and returning nil objects it causes`panic: runtime error: invalid memory address or nil pointer dereference` for clients.
```
```

Nil pointer safety

---

internal/redfishwrapper/virtual_media.go

We weren't checking vm.Inserted and on some HP ILOs this caused failures to eject even when there was nothing to eject. This makes it so that this call won't fail when there is nothing to eject.
```
```

Update virtual media ejecting:

---

go.mod
go.sum
providers/supermicro/errors.go
providers/supermicro/supermicro.go
providers/supermicro/supermicro_test.go
providers/supermicro/x11.go

- Enables login to these older SMC hardware along with identifying the hardware model from the board ID
For merge after https://github.com/bmc-toolbox/common/pull/25 
- Supermicro
- x11ssl-f
- x11scz-f
```
```

Enables support for supermicro x11ssl-f and x11scz-f

---

internal/redfishwrapper/virtual_media.go

As there can be multiple virtual media for a single manager, i.e. CD, DVD, USBStick, etc, we need to check for a matching supported type before ejecting or injecting. Also, added checking that the virtual media supports injecting before trying.
```
```

Improve virtual media ejecting and inserting:

---

providers/rpc/rpc.go

Since the RPC provider can be any arbitrary backend, the specific backend implementation should be responsible for handling any unsupported power state (by returning an error), not this library itself.
```
Removed power state limitations for RPC provider. All possible power states, not just "on", "off", or "cycle" are now supported by this provider.
```

Removed power state limitations from RPC provider

---

internal/ipmi/ipmi.go

Some implementations of ipmi, Dell for example, will error out if a machine is already off and an ipmitool power off command is issued. Error is `Command not supported in present state`. Checking the power state before issuing the power off command is also done in other ipmitool commands.
```
ipmitool: check power state before issuing a power off command.
```

Check power state before issuing power off for ipmi:
